// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

// / Default [FirebaseOptions] for use with your Firebase apps.
// /
// / Example:
// / ```dart
// / import 'firebase_options.dart';
// / // ...
// / await Firebase.initializeApp(
// /   options: DefaultFirebaseOptions.currentPlatform,
// / );
// / ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCgAwyDSqq12--2Hvb4q6NstpVEiKDbb_k',
    appId: '1:821084150126:web:b1ff17f3bb9d03fe98097f',
    messagingSenderId: '821084150126',
    projectId: 'ciggmmapp',
    authDomain: 'ciggmmapp.firebaseapp.com',
    storageBucket: 'ciggmmapp.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDaix0SQi6CR-LysxfC9DxaTV3P01zi0tM',
    appId: '1:821084150126:android:ca997825adb14f8398097f',
    messagingSenderId: '821084150126',
    projectId: 'ciggmmapp',
    storageBucket: 'ciggmmapp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyARwKq41urJDypbv8583bIIXwNGIsAMeLM',
    appId: '1:821084150126:ios:6807776a7044414998097f',
    messagingSenderId: '821084150126',
    projectId: 'ciggmmapp',
    storageBucket: 'ciggmmapp.appspot.com',
    iosBundleId: 'com.example.myApp1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyARwKq41urJDypbv8583bIIXwNGIsAMeLM',
    appId: '1:821084150126:ios:6807776a7044414998097f',
    messagingSenderId: '821084150126',
    projectId: 'ciggmmapp',
    storageBucket: 'ciggmmapp.appspot.com',
    iosBundleId: 'com.example.myApp1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCgAwyDSqq12--2Hvb4q6NstpVEiKDbb_k',
    appId: '1:821084150126:web:971e25fe5ac1d04b98097f',
    messagingSenderId: '821084150126',
    projectId: 'ciggmmapp',
    authDomain: 'ciggmmapp.firebaseapp.com',
    storageBucket: 'ciggmmapp.appspot.com',
  );
}